global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['${HOST}:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['${HOST}:9100']